/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "react-three-fiber";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/BOARD3_D.gltf");
  useFrame(({ clock }) => {
    group.current.rotation.y = clock.getElapsedTime() / 2;
  });
  return (
    <group ref={group} {...props} dispose={null} scale=".010">
      <mesh
        geometry={nodes.board2001.geometry}
        material={materials["Material.005"]}
        position={[0, 0, -0.93]}
        rotation={[0, 0, Math.PI / 2]}
        scale={2.15}
      >
        <mesh
          geometry={nodes.BOB004.geometry}
          material={materials["BOB.001"]}
          position={[-41.57, 1.51, -3.72]}
          rotation={[-Math.PI / 2, 1.57, 0]}
          scale={5.09}
        />
        <mesh
          geometry={nodes.logoWhite003.geometry}
          material={materials["logoWhite.001"]}
          position={[-3.55, 0, 5.06]}
          rotation={[2.98, -1.57, 1.42]}
          scale={10}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/BOARD3_D.gltf");
