/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "react-three-fiber";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/BOARD3_D.gltf");
  useFrame(({ clock }) => {
    group.current.rotation.y = clock.getElapsedTime() / 2;
  });
  return (
    <group ref={group} {...props} dispose={null} scale=".018">
      <mesh
        geometry={nodes.board4.geometry}
        material={materials["Material.005"]}
        rotation={[0.14, 1.53, 1.43]}
        scale={1.01}
      >
        <mesh
          geometry={nodes.BOB001.geometry}
          material={materials.BOB}
          position={[-38.28, 0.33, -1.54]}
          rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
          scale={5.08}
        />
        <mesh
          geometry={nodes.logoWhite001.geometry}
          material={materials["logoWhite.002"]}
          position={[23.38, -1.09, 6.62]}
          rotation={[0.18, -1.57, -1.43]}
          scale={16.35}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/BOARD1_D.gltf");
