/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "react-three-fiber";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/BOARD2_D.gltf");
  useFrame(({ clock }) => {
    group.current.rotation.y = clock.getElapsedTime() / 2;
  });
  return (
    <group ref={group} {...props} dispose={null} scale=".018">
      <mesh
        geometry={nodes.board3.geometry}
        material={materials["Material.005"]}
        rotation={[Math.PI, 1.55, -Math.PI / 2]}
      >
        <mesh
          geometry={nodes.BOB002.geometry}
          material={materials["BOB.001"]}
          position={[-37.76, -0.6, -3.24]}
          rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
          scale={4.93}
        />
        <mesh
          geometry={nodes.logoWhite002.geometry}
          material={materials["logoWhite.001"]}
          position={[14.26, -0.75, 3.06]}
          rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          scale={10}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/BOARD2_D.gltf");
