/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "react-three-fiber";
import { SmoothShading } from "three";

export default function Model({ ...props }) {
  const group = useRef();
  useFrame(({ clock }) => {
    group.current.rotation.y = clock.getElapsedTime() / 1.2;
  });
  const { nodes, materials } = useGLTF("/GrantD.gltf");
  return (
    <group ref={group} {...props} dispose={null} position={[0, 0.8, 0]}>
      <mesh
        geometry={nodes.board.geometry}
        material={materials["Material.001"]}
        rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
        scale={0.02}
      />
      <mesh
        geometry={nodes.logoWhite.geometry}
        material={materials.logoWhite}
        position={[0, -0.4, -0.04]}
        scale={0.2}
        rotation={[-Math.PI / 2, -Math.PI, 0]}
      />
    </group>
  );
}

useGLTF.preload("/GrantD.gltf");
