/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "react-three-fiber";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/GweebD.gltf");
  useFrame(({ clock }) => {
    group.current.rotation.y = clock.getElapsedTime() / 2;
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.logoWhite001.geometry}
        material={materials.logoWhite}
        position={[0, 1, -0.05]}
        scale={0.4}
        rotation={[-Math.PI / 2, -Math.PI, 0]}
      />
      <mesh
        geometry={nodes.Gweeb.geometry}
        material={materials["Material.001"]}
        rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
        scale={0.04}
      />
    </group>
  );
}

useGLTF.preload("/GweebD.gltf");
